app/bancodequestoes/urls.py
from __future__ import unicode_literals

from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'bancodequestoes'

urlpatterns = [
	#Home
	path('', views.HomeView.as_view(), name='home'),

	#Cadastro, Login e Logout
	path('cadastro/', views.UserCreateView.as_view(), name='cadastro'),

	path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),

	path('logout/', auth_views.LogoutView.as_view(), name='logout'),

	#Ver, editar e excluir Perfil
	path('perfil/', views.Perfil.as_view(), name='perfil'),

	path('perfiledit/<pk>/', views.Perfiledit.as_view(), name='perfiledit'),

	path('perfildelete/<pk>/', views.Perfildelete.as_view(), name='perfildelete'),

	#Cadastrar Disciplina
	path('disciplina/', views.CadastrarDisciplina.as_view(), name='disciplina'),

	#Ver, editar e excluir Disciplina
	path('suasdisciplinas/', views.SuasDisciplinas.as_view(), name='suasdisciplinas'),

	path('disciplinaedit/<pk>/', views.DisciplinaEdit.as_view(), name='disciplinaedit'),

	path('disciplinadelete/<pk>/', views.DisciplinaDelete.as_view(), name='disciplinadelete'),

	#Criar Questão
	path('criarquestao/', views.CriarQuestao.as_view(), name='criarquestao'),

	#Ver, editar e excluir Questão
	path('suasquestoes/',views.SuasQuestoes.as_view(), name='suasquestoes'),

	path('questaoedit/<pk>/', views.QuestaoEdit.as_view(), name='questaoedit'),

	path('questaodelete/<pk>/', views.QuestaoDelete.as_view(), name='questaodelete'),

	#Criar Prova
	path('disciplinas/', views.ListDisciplina.as_view(), name='disciplinas'),

	path('questoesdisciplina/<pk>/', views.QuestaoDisciplina.as_view(), name='questoesdisciplina'),
	
	path('criarprova/', views.CriarprovaView.as_view(), name='criarprova'),

	#Ver, editar e excluir Prova
	path('verprovas/', views.VerProvas.as_view(), name='verprovas'),

	path('provaedit/<pk>/', views.ProvaEdit.as_view(), name='provaedit'),

	path('provadelete/<pk>/', views.ProvaDelete.as_view(), name='provadelete'),

	#Resposta
	path('responderprova/', views.ResponderProva.as_view(), name='responderprova'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('app.bancodequestoes.urls'), name='bancodequestoes'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/cadastrardisciplina.html
{% extends 'home.html' %}

{% block content %}
	<form class="site-form" method="post">
		{% csrf_token %}	
		{{ form.as_p }}
		<input type="submit" value="Criar Disciplina">
	</form>
{% endblock %}

templates/disciplinadelete.html
{% extends 'home.html' %}

{% block content %}
	<form class="site-form" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Clique aqui se realmente deseja excluir esta disciplina"/>
	</form>
{% endblock %}

templates/home.html
{% load static from staticfiles %}

<!DOCTYPE html>

<html>

<head>

	<meta charset="utf-8">

	<title> BANCO DE QUESTÕES </title>

	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>

	<header class="wrapper">
		<nav>
			<ul>

				<li>
					<a href="{% url 'bancodequestoes:home' %}" class="hl"> Home </a>
				</li>
				
				{% if user.is_authenticated %}
				
				<li>
					<a href="{% url 'bancodequestoes:perfil' %}" class="hl"> Perfil </a>
				</li>

				<li>
					<a href="{% url 'bancodequestoes:disciplina' %}" class="hl"> Cadastrar Disciplina </a>
				</li>

				<li>
					<a href="{% url 'bancodequestoes:suasdisciplinas' %}" class="hl"> Suas Disciplinas </a>
				</li>

				<li>
					<a href="{% url 'bancodequestoes:criarquestao' %}" class="hl"> Criar Questão </a>
				</li>

				<li>
					<a href="{% url 'bancodequestoes:suasquestoes' %}" class="hl"> Suas Questões </a>
				</li>

				<li>
					<a href="{% url 'bancodequestoes:disciplinas' %}" class="hl"> Criar Prova </a>
				</li>

				<li>
					<a href="{% url 'bancodequestoes:verprovas' %}" class="hl"> Suas Provas </a>
				</li>

				<li>
					<a href="{% url 'bancodequestoes:responderprova' %}" class="hl"> Responder Prova </a>
				</li>

				<li>
					<a href="{% url 'bancodequestoes:logout' %}" class="hl"> Sair </a>
				</li>

				{% else %}

				<li>
					<a href="{% url 'bancodequestoes:cadastro' %}" class="hl"> Cadastrar-se </a>
				</li>

				<li>
					<a href="{% url 'bancodequestoes:login' %}" class="hl"> Entrar </a>
				</li>

				{% endif %}

			</ul>
		</nav>
	</header>

	{% block content %}

	{% endblock %}

</body>

</html>

templates/login.html
{% extends 'home.html' %}

{% block content %}
<form class='site-form' method="post">
	{% csrf_token %}
	<p class="label"> Usuário </p>
	<input type="text" name="username" class="field"/>
	<p class="label">Senha</p>
	<input type="password" name="password" class="field"/>
	<input type="submit" class="button" value="Login"/>
	
</form>
{% endblock %}

templates/perfildelete.html
{% extends 'home.html' %}

{% block content %}
	<form class="site-form" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Clique aqui se realmente desejar excluir esse perfil"/>
		<p> Lembre-se: se você excluir um perfil no qual você esteja logado, você sairá da aplicação e perderá quaisquer dados relacionados a ele. </p>
	</form>
{% endblock %}

templates/provadeleteform.html
{% extends 'home.html' %}

{% block content %}
	<form class="site-form" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Clique aqui se realmente deseja excluir esta prova"/>
	</form>
{% endblock %}

templates/provaeditform.html
{% extends 'home.html' %}

{% block content %}
	<form class="site-form" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Alterar Prova"/>
	</form>
{% endblock %}

templates/questaodelete.html
{% extends 'home.html' %}

{% block content %}
	<form class="site-form" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Clique aqui se realmente deseja excluir esta questão"/>
	</form>
{% endblock %}

templates/questaoedit.html
{% extends 'home.html' %}

{% block content %}
	<form class="site-form" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Alterar Questao"/>
	</form>
{% endblock %}

templates/questoesdisciplina.html
{% extends 'home.html' %}

{% block content %}
	<p><a href="{% url 'bancodequestoes:criarprova' %}"> Crie sua prova </a></p>
	<h2> Questões da disciplina de <b> {{object.name}} </b> </h2>
	{% for questao in questoes %}
		{% if questao.prof == request.user %}
			{% if questao.subject.pk == object.pk %}
				<br>
				<p> {{questao.enunciation}}</p>
				<p> {{questao.alternative1}}</p>
				<p> {{questao.alternative2}}</p>
				<p> {{questao.alternative3}}</p>
				<p> {{questao.alternative4}}</p>
				<p> {{questao.alternative5}}</p>
				<br>
				<p> <b>_______________________________________________________________________________________________________________________________________________ </b></p>
			{% endif %}
		{% endif %}
	{% endfor %}
{% endblock %}

templates/responderprova.html
{% extends 'home.html' %}

{% block content %}
	<form class='site-form' method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Responder Prova">
		 
	</form>
		
{% endblock %}

templates/suasdisciplinas.html
{% extends 'home.html' %}

{% block content %}
	<h2> <b> Suas Disciplinas: </b> </h2>
	{% for object in object_list %}
		{% if object.prof == request.user %}
			<h2> <b> {{object.name}} </b> </h2>
			<h3> {{object.description}} </h3>
			<p> <a href="{% url 'bancodequestoes:disciplinaedit' object.pk %}"> Editar Disciplina </a> <p/>
			<p> <a href="{% url 'bancodequestoes:disciplinadelete' object.pk%}"> Excluir Disciplina </a> </p>

			<p> <b>_______________________________________________________________________________________________________________________________________________ </b></p>
		{% endif %}
	{% endfor %}
{% endblock %}

templates/suasquestoes.html
{% extends 'home.html' %}

{% block content %}
	<h2> <b> Suas Questões: </b> </h2>
	{% for object in object_list %}
		{% if object.prof == request.user %}
			<h3> <b> {{object.enunciation}} </b> </h3> 
			<p> <img src="/media/{{object.image}}"></p>
			<p> <b> Alternativas: </b></p>
			<p> a) {{object.alternative1}} </p>
			<p> b) {{object.alternative2}} </p>
			<p> c) {{object.alternative3}} </p>
			<p> d) {{object.alternative4}} </p>
			<p> e) {{object.alternative5}} </p>
			<p> Alternativa correta: <b> {{object.answer}} </b> </p>
			<p> <a href="{% url 'bancodequestoes:questaoedit' object.pk %}"> Editar Questão </a> <p/>
			<p> <a href="{% url 'bancodequestoes:questaodelete' object.pk%}"> Excluir Questão </a> </p>
		{% endif %}
	{% endfor %}
{% endblock %}

templates/verprovas.html
{% extends 'home.html' %}

{% block content %}
	<h2> <b> Suas Provas: </b> </h2>
	{% for object in object_list %}
		{% if object.prof == request.user %}
			<h2> <b> {{object.title}} </b> </h2>



			<p> <b> Enunciado: 1) {{object.question1}} </b> </p>
			<p> Imagem: <img src="/media/{{object.question1.image}}"></p>
			<p> Alternativas: </p>
			<p> a) {{object.question1.alternative1}}</p>
			<p> b) {{object.question1.alternative2}}</p>
			<p> c) {{object.question1.alternative3}}</p>
			<p> d) {{object.question1.alternative4}}</p>
			<p> e) {{object.question1.alternative5}}</p>
			
			<p> <b> Enunciado: 2) {{object.question2}} </b> </p>
			<p> Imagem: <img src="/media/{{object.question2.image}}"></p>
			<p> Alternativas: </p>
			<p> a) {{object.question2.alternative1}}</p>
			<p> b) {{object.question2.alternative2}}</p>
			<p> c) {{object.question2.alternative3}}</p>
			<p> d) {{object.question2.alternative4}}</p>
			<p> e) {{object.question2.alternative5}}</p>
			
			<p> <b> Enunciado: 3) {{object.question3}} </b> </p>
			<p> Imagem: <img src="/media/{{object.question3.image}}"></p>
			<p> Alternativas: </p>
			<p> a) {{object.question3.alternative1}}</p>
			<p> b) {{object.question3.alternative2}}</p>
			<p> c) {{object.question3.alternative3}}</p>
			<p> d) {{object.question3.alternative4}}</p>
			<p> e) {{object.question3.alternative5}}</p>
			
			<p> <b> Enunciado: 4) {{object.question4}} </b> </p>
			<p> Imagem: <img src="/media/{{object.question4.image}}"></p>
			<p> Alternativas: </p>
			<p> a) {{object.question4.alternative1}}</p>
			<p> b) {{object.question4.alternative2}}</p>
			<p> c) {{object.question4.alternative3}}</p>
			<p> d) {{object.question4.alternative4}}</p>
			<p> e) {{object.question4.alternative5}}</p>
			
			<p> <b> Enunciado: 5) {{object.question5}} </b> </p>
			<p> Imagem: <img src="/media/{{object.question5.image}}"></p>
			<p> Alternativas: </p>
			<p> a) {{object.question5.alternative1}}</p>
			<p> b) {{object.question5.alternative2}}</p>
			<p> c) {{object.question5.alternative3}}</p>
			<p> d) {{object.question5.alternative4}}</p>
			<p> e) {{object.question5.alternative5}}</p>
			
			<p> <a href="{% url 'bancodequestoes:provaedit' object.pk %}"> Editar Prova </a> </p>
			<p> <a href="{% url 'bancodequestoes:provadelete' object.pk %}"> Excluir Prova </a> </p>

			<p> <b>_______________________________________________________________________________________________________________________________________________ </b></p>
		{% endif %}
	{% endfor %}
{% endblock %}